import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header";
import Navber from "@/components/shared/Navber";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" className="h-full antialiased">
      <body
        className={`${poppins.className} min-h-full flex flex-col container mx-auto`}
      >
        <Header />
        <Navber />
        <main>{children}</main>
      </body>
    </html>
  );
}
